name: Feature request
description: Suggest an idea
labels: [type:feature]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: What is the feature and why?
    validations:
      required: true
