name: CI (Blueprint Validate)

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install CUE (Go 1.24+, per cue requirements)
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install CUE
        run: |
          go install cuelang.org/go/cmd/cue@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Type-check blueprint
        run: cue vet blueprint.cue schema.cue

      - name: Export files map
        run: cue export generate.cue -e files -o files.json

      - name: Rebuild outputs and check drift
        run: |
          set -e
          python3 - << 'PY'
          import json, os, pathlib
          data = json.load(open('files.json','r',encoding='utf-8'))
          for path, content in data.items():
              d = os.path.dirname(path)
              if d and d != '.': pathlib.Path(d).mkdir(parents=True, exist_ok=True)
              shadow = pathlib.Path('.blueprint_shadow') / path
              shadow.parent.mkdir(parents=True, exist_ok=True)
              shadow.write_text(content or '', encoding='utf-8')
          PY
          if ! diff -ru .blueprint_shadow . | grep -E "^(Only in \.blueprint_shadow|diff -ru \.blueprint_shadow)" -q; then
            echo "✅ No drift detected."
          else
            echo "❌ Drift detected between generated outputs and committed files."
            echo "   Run the generator (CI or Codespaces) and commit the updates."
            exit 1
          fi
